# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: DeepSpace
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    
    - name: Build with Maven
      run: mvn -B package --file ${{github.workspace}}/pom.xml

       
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
       name: Deepspace-artifact
       path: ${{github.workspace}}/target/*.war
  Deploy:
    name: On Prem Deploy
   
    runs-on: sro-runner
    needs: build 
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: Deepspace-artifact
          path: C:\Users\subharanjano\Deepspace
      
